version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region eu-central-1 | docker login --username AWS --password-stdin 471112585965.dkr.ecr.eu-central-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - docker build -t flask_gpt_ec2 .
      - docker tag flask_gpt_ec2:latest 471112585965.dkr.ecr.eu-central-1.amazonaws.com/python/flask_gpt_ec2:latest
      - docker push 471112585965.dkr.ecr.eu-central-1.amazonaws.com/python/flask_gpt_ec2:latest
  post_build:
    commands:
      - echo Writing image definitions file...
      - printf '[{"name":"flask_gpt_ec2","imageUri":"471112585965.dkr.ecr.eu-central-1.amazonaws.com/python/flask_gpt_ec2:latest"}]' > imagedefinitions.json

artifacts:
  files:
    - appspec.yml
    - post_script.sh
    - imagedefinitions.json
